name: Man10Anni
version: ${project.version}
main: red.man10.man10anni
authors: [takatronix]
description: Man10 Anni Plugin
website: http://man10.red
commands:
    annitop:
        description: トップAnniPlayerを表示 / Show Top Anni players
        usage: /annitop [number of top players]
    annixp:
        description: Anni XPを表示 Show AnniXp
        usage: /annixp [Player]
    anniexchange:
        description: AnniXpをアイテムに交換 Exchange AnniXp to special item
        usage: /anniexchange
    manni:
        description: man10 anni command
        usage: /manni